name: Lol

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 10:00 UTC
  workflow_dispatch:

jobs:
  commit-streak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "Green Graph Bot"
          git config user.email "bot@example.com"

      - name: Generate commits (and Sunday cleanup)
        run: |
          DAY=$(date +%u)  # 7 = Sunday
          if [ "$DAY" -eq 7 ]; then
            echo "Sunday cleanup: clearing streak.txt"
            > streak.txt
          fi

          N=$(( (RANDOM % 5) + 1 ))  # 1 to 5 commits
          echo "Generating $N commits"
          for i in $(seq 1 $N); do
            echo "$RANDOM" >> streak.txt
            git add -f streak.txt
            git commit -m "Green commit $i on $(date)"
          done

      - name: Push commits
        run: git push origin main
